; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = ota_upload

[common]
platform = espressif8266
board = esp01_1m
framework = arduino
monitor_speed = 115200
lib_deps = 
    bblanchon/ArduinoJson@^7.2.2
	sparkfun/SparkFun BME280@^2.0.9

[env:ota_upload]
extends = common
upload_resetmethod = ck
board_build.flash_mode = dout
upload_protocol = espota
; For device: esp8266-811dca._arduino._tcp.local.
; Figure out the IP address of your device and use it here
; use http://routerlogin.net/ or similar to find the IP address of your device
upload_port = 192.168.8.4

[env:serial_upload]
extends = common
upload_port = COM4
